CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;


CREATE TABLE IF NOT EXISTS city (
  ID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL UNIQUE ,
  PRIMARY KEY (ID)
);

INSERT IGNORE INTO city (name) values ('Paris'), ('Moscow'), ('Milan');


